name: Build Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x gradlew
      - name: Run Gradle build
        run: ./gradlew MyFirstKotlinPlugin:build
      - name: Print file structure
        run: ls -la MyFirstKotlinPlugin/build/libs/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyFirstKotlinPlugin-release
          path: MyFirstKotlinPlugin/build/libs/*.jar


